### PR TITLE
added RRType requests in IANA Considerations

### PR DESCRIPTION
**Pull request by moonshiner**
Make specific IANA requests in the IANA Considerations section

### CODE REVIEW

**Comment by moonshiner** [comment]
I updated this with the IANA Values that have been assigned.

**Comment by bemasc** [comment]
This looks good but maybe we should hold off on it until after WGLC, just in case there are any last-minute changes?

**Comment by tfpauly** [comment]
@bemasc the allocations are already made, so we may as well mention the values, right?

**Comment by moonshiner** [comment]
We should mention the values as they are set by IANA.

**Pull request merged**
