### PR TITLE
s/echconfig/ech/

### PR DESCRIPTION
**Pull request by bemasc**
See #298 and https://github.com/tlswg/draft-ietf-tls-esni/pull/391

### CODE REVIEW

**Review by enygren — APPROVED** [review]

**Comment by marka63** [comment]
This should not be happening.  You are abusing the code point allocation.  The record format is supposed to be FIXED when the code point is allocated.  I complained before the code point was allocated that it was not the right time in the development process to perform the allocation.  When the code point is allocated the DNS record should be stable. That is both WIRE and PRESENTATION formats.  Remember master file format is a INTERCHANGE specification.

The DNS has a reserved range for private types which are fine for experimentation.

Mark

> On 27 Feb 2021, at 07:13, Benjamin M. Schwartz <notifications@github.com> wrote:
> 
> See #298 and tlswg/draft-ietf-tls-esni#391
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/MikeBishop/dns-alt-svc/pull/299
> 
> Commit Summary
> 
> 	• s/echconfig/ech/
> File Changes
> 
> 	• M draft-ietf-dnsop-svcb-https.md (60)
> Patch Links:
> 
> 	• https://github.com/MikeBishop/dns-alt-svc/pull/299.patch
> 	• https://github.com/MikeBishop/dns-alt-svc/pull/299.diff
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

-- 
Mark Andrews, ISC
1 Seymour St., Dundas Valley, NSW 2117, Australia
PHONE: +61 2 9871 4742              INTERNET: marka@isc.org

**Comment by enygren** [comment]
Does this argue that we should change the codepoint and abandon echconfig/5 as part of the switch to the "ech" key name?  (In some ways this is happening due to the dependent ECH draft making changes.)  That then makes this a key addition rather than a change.

**Comment by ericorth** [comment]
+1.  If there's any concern whatsoever about compatibility problems from renaming "echconfig", let's add a new service parameter codepoint for the renamed param.  In a quick review of the current draft, I don't see any reason that would break stability of SVCB/HTTPS themselves.  I could see an argument if "echconfig" were in the automatically-mandatory list, but it's not.

**Comment by bemasc** [comment]
As a practical matter, I don't think we need to go through a deprecation procedure.  The "echconfig" contents are defined by a draft (draft-ietf-tls-esni) that is not finished, and indeed has multiple breaking changes in progress.  I don't think anyone who is using "echconfig" in a zone today expects it to be interoperable.  The only deployment I'm aware of exists specifically for interoperability testing of draft versions of ECH, and that is the only appropriate use at this stage.

As for the Early Allocation rules, note that "echconfig" is not part of the SVCB draft standard presentation format.  Rather, it is a proposed entry in an IANA registry that doesn't exist yet.

While I think it's annoying to have to burn a codepoint in order to change the name, I'm happy to do so if necessary.  If that's the consensus, I think we might as well wait until the ECH draft is final before making any change, to avoid having to do this again.

**Comment by enygren** [comment]
How do we get to consensus here?  Options seem to be:

1. Stick with echconfig and current codepoint.  (Not preferable.)
2. Switch to ech and use new codepoint.   (Burns a codepoint, not strictly necessary.)
3. Switch to ech and keep existing codepoint.   (Changes the presentation to wire format mapping of an existing codepoint.)

I could go with either 2/3.  @marka63 seems to strongly prefer 2.  @bemasc seems to strongly prefer 3.

**Comment by bemasc** [comment]
I am fine with any of these three things.  From most preferred to least: 3, 1, 2.  My main point is that, if we go with 2, we should delay the switch as long as possible, to wait until after any possible compatibility-breaking changes in ECH.  (Whereas if we go with 3, we should do it as soon as possible to minimize disruption.)

**Comment by enygren** [comment]
What about going with 2, but leaving instructions for that switch to happen once TLS ECH passes its last-call? 
Can we do something like updating the text to use "ech" but leave the codepoint listed as "to-be-assigned"
and then assign it shortly before publication?

**Comment by bemasc** [comment]
@enygren That sounds complicated.  I don't know how to explain it to the RFC Editor, and I don't know what advice I would give to an implementer.  It seems a lot easier to just change nothing (which might be less confusing after s/ECHConfigs/ECHConfigList/).

**Comment by davidben** [comment]
Changing nothing will remain confusing because ECH has a structure called ECHConfig, and that is *not* the structure that goes in SVCB. The intent hasn't been for SVCB to contain an ECHConfig since draft-ietf-tls-esni-07, the very first draft that used the ECH name. The "echconfig" name was a mistake from the beginning.

Given SVCB and ECH are getting published at different times, should the code point definition just be moved out of SVCB and into ECH? Though this is somewhat moot because, on the compatibility side, the ECHConfigList structure is already internally versioned.

**Comment by bwelling** [comment]
An alternative solution could be to change the parameter name to `ech`, and support `echconfig` as an alias.  I think that would satisfy at least some backwards compatibility issues.

**Comment by bemasc** [comment]
Most of the SVCB parameters are singular-name, multiple-value, so `echconfig=<ECHConfigList>` seems to fit the pattern.  However, I'm certainly happy to change it if it still seems confusing.

Maintaining an alias is possible, but I would rank it lower than the other three options.  It makes "echconfig" different from all other parameters, it seems to create a permanent burden to deal with a temporary problem, and I'm not sure it actually satisfies the desire for zone-file compatibility with existing draft implementations.  (Of course, burning the codepoint is even worse for zone file compatibility.)

**Comment by marka63** [comment]
You have already introduced incompatible changes with alpn comma escape processing.  All these incompatible changes are, in part, why BIND hasn't shipped a version which supports these record types despite the requests for them from our customers.

Whether the type codes and mnemonics are already burnt or not I don't know.  Every vendor that has already shipped parsers could treat the changes as incompatible bug fixes and one could get away with it.

**Comment by sayrer** [comment]
> How do we get to consensus here? Options seem to be:
> 
> 1. Stick with echconfig and current codepoint.  (Not preferable.)
> 2. Switch to ech and use new codepoint.   (Burns a codepoint, not strictly necessary.)
> 3. Switch to ech and keep existing codepoint.   (Changes the presentation to wire format mapping of an existing codepoint.)
> 
> I could go with either 2/3. @marka63 seems to strongly prefer 2. @bemasc seems to strongly prefer 3.

3 is good, 2 is fine but seems a bit officious, and 1 seems kind of bad but livable.

So, they're all ok.

**Comment by chris-wood** [comment]
Like @enygren, I'm fine with 3 or 2, but lean towards 3 given the state of this record and its users.

**Comment by MikeBishop** [comment]
I prefer 3.  There's a certain appeal to just letting ECH register the codepoint in their doc, but that seems orthogonal to this question.

**Comment by davidben** [comment]
Yeah, moving the registration mostly relates if we're doing (2) + delay. If we do the delay thing, we may as well move the codepoint IMO.

I also prefer (3), in which case I agree it's orthogonal and doesn't matter much.

**Comment by bemasc** [comment]
For comparison, I've created a draft meta-PR that allocates a new codepoint for "ech": #316.  Hopefully this helps people weigh the options here in terms of complexity, compatibility, and potential for confusion.

**Comment by tfpauly** [comment]
I prefer 3 as well, FWIW.

**Comment by moonshiner** [comment]
I'm with option 3 as well.

**Comment by bemasc** [comment]
OK, I'm going to merge this as-is and publish a new version for further discussion.

**Comment by marka63** [comment]
Hello
I have a business partnership proposal for you. Contact me on my
personal email for more details please :
***@***.***


Regards
Saif

**Comment by marka63** [comment]
Hello
I have a business partnership proposal for you. Contact me on my
personal email for more details please :
***@***.***


Regards
Saif

**Pull request merged**
