### PR TITLE
ESNIKeys is now ESNIConfig

### PR DESCRIPTION
**Pull request by bemasc**
Matches the terminology from https://github.com/tlswg/draft-ietf-tls-esni/pull/187

@chris-wood FYI

### CODE REVIEW

**Comment by chris-wood** [comment]
LGTM -- thanks, @bemasc!

**Comment by bemasc** [comment]
It looks like that PR hasn't landed yet, so this one should probably wait until it's merged.

**Comment by chris-wood** [comment]
@bemasc the ESNI draft PR has been merged, so this one should be good to go. One thing we might want to consider is the option for the field to represent a set of configurations, so perhaps we can rename this to "esniconfigs" and note that it's the concatenation of one or more ESNIConfig structures?

**Comment by bemasc** [comment]
Thanks for the reviews.

> unless we want to just call it "esni" ?

I would be OK with renaming to "esni", but I do wonder if it could be confusing, because the contents of this field are not the "encrypted SNI".  I would defer to the ESNI authors on preferred terminology.

> perhaps we can rename this to "esniconfigs" and note that it's the concatenation of one or more ESNIConfig structures

I would be OK with this, but it seems like a nontrivial change so I'm not going to attempt it in this PR.  I would also want to think a bit about what the use case is.  It occurs to me that a client with multiple `ESNIConfig`s could potentially have some kind of fallback behavior (but how does that interact with `esni_retry_request`?) or it could even put multiple `encrypted_server_name` extensions in the ClientHello.

**Pull request merged**
