### PR TITLE
Clarify self-consistency rules

### PR DESCRIPTION
**Pull request by bemasc**
Requested in https://github.com/MikeBishop/dns-alt-svc/pull/284/files#r552202056

### CODE REVIEW

**Comment by bemasc** [comment]
@ericorth Does this address your concern?

**Comment by ericorth** [comment]
> @ericorth Does this address your concern?

Yes.  It does so nicely.  Thanks.

Further suggestion: We should call out "would make the record not self-consistent" or something like that for the alpn/no-default-alpn case we were calling out as "invalid" before (and any other cases we know of).  Good to keep the language in the draft consistent and precise ("malformed" vs "invalid" vs "not self-consistent").

**Comment by bemasc** [comment]
> Further suggestion: We should call out "would make the record not self-consistent" or something like that for the alpn/no-default-alpn case we were calling out as "invalid" before (and any other cases we know of). Good to keep the language in the draft consistent and precise ("malformed" vs "invalid" vs "not self-consistent").

Agreed; I was just trying to avoid a collision with #284.

**Comment by enygren** [comment]
One thing that does get messy here is how to handle new types of keys.  A zone file parser clearly can't handle keyNNNN form SvcParams, but for clients it seems like there could be cases where a new non-mandatory SvcParm shows up that is declared in its spec to conflicts with some other SvcParam.  There is no way for clients which are aware of these to reject the RR.  We also want to avoid cases where clients confused by some new SvcParams throw out the entire RRset and cause compatibility issues.  I'm not sure what we might want to add to help here?

**Comment by bemasc** [comment]
> There is no way for clients which are aware of these to reject the RR.

Do you mean "not aware"?

> I'm not sure what we might want to add to help here?

I adjusted the text.  Is it clearer now?

**Review by enygren — APPROVED** [review]

**Pull request merged**
